### ISSUE TITLE
A Good Readme

### ISSUE THREAD

**Issue by Donnie** [tarique93102/react-redux-starter-template#1]
A good and exhaustive readme would really be helpful.

It may include things like how to start, how to add new routes, how to organise files, etc

**Comment by tejazz** [comment]
I am planning to update this repository completely since it has been quite some time but I guess I had written an article on the setup.

https://codeburst.io/react-redux-a-boilerplate-template-to-start-reacting-80e0349bef1?source=---------6------------------

However, an exhaustive readme is the right way to go.
